---
- hosts: all
  tasks:
  - name: Update apt-cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install some packages
    apt:
      name: "{{ item }}"
      state: present
      force_apt_get: True
    with_items:
      - aptitude
      - zfs-dkms
